// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhphsdkfncfvajzsdlnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocGhzZGtmbmNmdmFqenNkbG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTczNDYsImV4cCI6MjA1ODgzMzM0Nn0.X1KbHlnRKS47GzMxQRX7LfvFfzXny0LB6itGROXvniM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);